apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    name: grafana
  sessionAffinity: None
  type: ClusterIP
